### ISSUE TITLE
Api differences autoqueue vs servers

### ISSUE THREAD

**Issue by emmoistner** [ErlendEllingsen/Elysium-Status#5]
### Issue
`autoqueue` response looks like it getting posted from [EAQ](https://github.com/ErlendEllingsen/Elysium-Auto-Queue) and cached to elysium status keeper.

That would be fine if the original keys were consistent or provided by autoqueue response. 
I'm currently using a crappy name lookup to get around this.

### Possible solutions
 *  Adding consistent ids to the cache autoqueue data on the `/auto-queue-update` endpoint
 * change EAQ to send ids in it's post to `/auto-queue-update`
 * change autoqueue body to use an object instead of an array
### possible response 
```js
// autoqueue Response (Option 1 or Option 2)
"servers": [
  {
    "name": "Elysium PVP",
    "id": "elysium_pvp",
    "queueAvailable": true,
    "queue": 3507,
    "last_updated": "2017-01-13T01:39:48.0415184+01:00"
  },
  // ...
}
```
If you have any ideas or thoughts I would love to hear them

**Comment by ErlendEllingsen** [comment]
Will be a better solution than current. Will probably be: **change autoqueue body to use an object instead of an array**

**Comment by emmoistner** [comment]
cool, keep me updated

**Comment by ErlendEllingsen** [comment]
autoqueue-data is now in object format. (https://elysiumstatus.com/fetch-queue)
